### ISSUE TITLE
Found Inf or NaN global norm. 

### ISSUE THREAD

**Issue by roadtorajendra** [Danyleb/Lstm-Variational-Auto-encoder#3]
InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had Inf values

I've been getting this error in the latest commit making the loss absurdly negative number or Nan. I tested with the previous versions the computation of loss is fine.

**Comment by AldrichLeo** [comment]
me too，do u resolve this question?

**Comment by roadtorajendra** [comment]
The issue was not resolved in the latest commit, instead I used the previous commit which works without this error

**Comment by AldrichLeo** [comment]
which code? can u send the link to me？ thank you

**Comment by TimyadNyda** [comment]
It should be ok by now :)

**Comment by roadtorajendra** [comment]
> which code? can u send the link to me？ thank you

I think I used 2018 commintted code. Now Dany has fixed the issue for the latest release.
